### ISSUE TITLE
v.8.0.0 produce error on startup no db unlock possible

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [xatupal/KeeTheme#46] opened 2021-04-28 06:29 UTC
After upgrade to v.8.0.0 produce error on startup no db unlock possible. If I delete plugin plgx all working as normal.

`KeeTheme
    Assembly-Version: 0.8.0.0.
    Win32-Version: 0.8.0.0.`

```
`Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.InvalidOperationException: Der Fensterhandle ist bereits vorhanden.
   bei System.Windows.Forms.NativeWindow.CheckReleased()
   bei System.Windows.Forms.NativeWindow.AssignHandle(IntPtr handle, Boolean assignUniqueID)
   bei KeeTheme.Decorators.RichTextBoxNativeWindow..ctor(RichTextBox richTextBox)
   bei KeeTheme.Decorators.RichTextBoxDecorator..ctor(RichTextBox richTextBox, ITheme theme)
   bei KeeTheme.KeeTheme.Apply(RichTextBox richTextBox)
   bei KeeTheme.KeeTheme.Apply(Control control)
   bei KeeTheme.ControlVisitor.Visit(ControlCollection formControls)
   bei KeeTheme.ControlVisitor.Visit(ControlCollection formControls)
   bei KeeTheme.ControlVisitor.Visit(ControlCollection formControls)
   bei KeeTheme.ControlVisitor.Visit(ControlCollection formControls)
   bei KeeTheme.ControlVisitor.Visit(ControlCollection formControls)
   bei KeeTheme.ControlVisitor.Visit(ControlCollection formControls)
   bei KeeTheme.ControlVisitor.Visit(ControlCollection formControls)
   bei KeeTheme.KeeThemeExt.ApplyThemeInOpenForms()
   bei KeeTheme.KeeThemeExt.InitializeTheme()
   bei KeeTheme.KeeThemeExt.HandleTriggerSystemRaisingEvent(Object sender, EcasRaisingEventArgs e)
   bei KeePass.Ecas.EcasTriggerSystem.RaiseEventObj(EcasEvent e, EcasPropertyDictionary props)
   bei KeePass.Forms.MainForm.OnFormLoad(Object sender, EventArgs e)
   bei System.Windows.Forms.Form.OnLoad(EventArgs e)
   bei System.Windows.Forms.Form.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
   bei KeePass.Forms.MainForm.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4341.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------
KeePass
    Assembly-Version: 2.47.0.21109.
    Win32-Version: 2.47.0.0.
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.exe.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4300.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4341.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4190.0 built by: NET48REL1LAST_B.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4341.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3752.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
`
```

looks like dupe of #45 45

**Comment by xatupal** [comment] 2021-04-28 07:09
Thanks for info. It's a duplicate of [#45](https://github.com/xatupal/KeeTheme/issues/45).
The difference is that you have no other plugins installed (according to the logs).
Looks like the error is nondeterministic. I'll try to track it again. 
For now please download [v0.8.1](https://github.com/xatupal/KeeTheme/releases/tag/v0.8.1) where the problem with crash is fixed.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment] 2021-04-28 08:44
Sorry, the log is truncated and other Plugins are installed!

I will try v0.8.1 <https://github.com/xatupal/KeeTheme/releases/tag/v0.8.1>  ty for fixing.

Choco said:

keepass-plugin-keetheme v0.8.0 is the latest version available based on your source(s).

**Comment by xatupal** [comment] 2021-04-28 18:54
I forgot about the Choco. Fixed.

It would be very helpful if you were able to find a plugin that is causing the conflict.
I could analyze the code of that plugin and maybe find a solution so that they can coexist together.

**Comment by xatupal** [comment] 2022-11-11 21:15
I'm closing the ticket because the conflict has not been found.

**Closed by xatupal** 2022-11-11 21:15 UTC
